config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pokemons#index"
  resources :pokemons, only: [:index, :show, :new, :create, :destroy] do
    resources :rentings, only: [:new, :create, :index]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'dashboard', to: 'pages#dashboard'
  get 'memory', to: 'pages#memory'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :rentings, dependent: :destroy
  has_one_attached :photo

  enum sexe: { Female: 0, Male: 1}

  validates :name, presence: true
  validates :price_per_day, presence: true
  validates :sexe, presence: true


  pg_search_scope :search_by_name_and_main_type_and_main_power,
    against: [:name, :main_type, :main_power],
    using: {
      tsearch: { prefix: true }
}

end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pokemons, dependent: :destroy
  has_many :rentings, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def memory
    @pokelist = Pokemon.all.sample(12) # Prendi tutti i Pokémon dal database e seleziona 12 casualmente
    @cards = (@pokelist + @pokelist).shuffle # Crea il mazzo e lo mescola
  end

end



# @pokemons = Pokemon.sample.limit(12)

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    if params[:query].present?
      @pokemons = Pokemon.search_by_name_and_main_type_and_main_power(params[:query])
    else
      @pokemons = Pokemon.all
    end
    @pokemon = Pokemon.new
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @renting = Renting.new
    # @rentings = @pokemon.rentings.include(:user)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

   private

  def pokemon_params
    params.require(:pokemon).permit(:name)
  end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pokemon, only: [:index, :show, :new, :create, :edit]
  before_action :set_renting, only: [:show, :edit]

  def index
    #@rentings = @Pokemon.rentings
    @rentings = current_user.rentings
  end

  def show
    @renting = @pokemon.rentings.find(params[:id])
  end

  def new
    @renting = Renting.new
  end

  def create
    # selected_dates = params[:renting][:start_date] #.split(" to ")
    # start_date = selecrrted_dates[0]
    # end_date = selected_dates[1]
    @renting = Renting.new(renting_params)
    @renting.pokemon = @pokemon
    @renting.user = current_user
    if @renting.save!
      redirect_to pokemon_path(@pokemon)
    else
      redirect_to pokemon_path(@pokemon)
    end

  end

  def edit
    @renting = @pokemon.rentings.find(params[:id])
  end

  private

  def renting_params
    params.require(:renting).permit(:start_date, :end_date)
  end

  def set_renting
    @renting = Renting.find(params[:id])
  end

  def set_pokemon
    @pokemon = Pokemon.find(params[:pokemon_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="background-image: url('<%= image_path("map-bg") %>'); background-size: cover; background-repeat: no-repeat;">

    <%= render "components/navbar" %>
    <div class="mt-3 mb-3">
      <div class="container border border-4 border-dark rounded-4 p-3 " style="height: 100%; background-color: rgb(239 0 23 / 75%)">
        <%= yield %>
      </div>
    </div>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76A8z8X6iOk6E9iV+HIjCp/fvGYW+0J8Hh99p6tqVQ+uV4F8hzH9vF7Y4N8hlU2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/dashboard.html.erb
<% if current_user.rentings.any? %>
  <h2 class="text-center">My team: </h2>
  <div class="d-flex justify-content-around bg-white m-4 p-4 border border-warning border-3 rounded-4">
    <% current_user.rentings.each do |renting| %>
<div data-bs-toggle="popover"
     data-bs-placement="right"
     data-bs-custom-class="custom-popover"
     data-bs-title="Custom popover"
     data-bs-content="This popover is themed via CSS variables.">
        <%= cl_image_tag renting.pokemon.image_url,
                         crop: :thumb,
                         gravity: :faces,
                         height: 50,
                         width: 50,
                         class: "border border-3 border-danger rounded-circle bg-dark" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>


<%= link_to "See them all", pokemons_path, class:"btn btn-primary"%>

app/views/pages/memory.html.erb
<%# <div class="bounce-on-hover">
  <div data-action="click->toggle#fire" class="wrap">
    <div class="ball-container">
      <div class="ball">
       <div class="upper-half"></div>
       <div class="lower-half"></div>
       <div class="center-circle"></div>
     </div>
    </div>
  </div>

  <p>New game!</p>
</div> %>

<!-- Element to toggle -->
<div data-toggle-target="togglableElemBis" class="d-block">
  <%= render "components/card-memory", pokemons: @pokemons %>
</div>

app/views/pokemons/create.html.erb
<h1>Pokemons#create</h1>
<p>Find me in app/views/pokemons/create.html.erb</p>

app/views/pokemons/destroy.html.erb
<h1>Pokemons#destroy</h1>
<p>Find me in app/views/pokemons/destroy.html.erb</p>

app/views/pokemons/edit.html.erb
<h1>Pokemons#edit</h1>
<p>Find me in app/views/pokemons/edit.html.erb</p>

app/views/pokemons/index.html.erb
<h1>Hello young <%= current_user.first_name %></h1>

<%= render "components/background", pokemons: @pokemons %>



<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: pokemons_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control me-3",
            placeholder: "Type a Pokemon name or type"
        %>
      <%= link_to type: "submit" do %>
        <%= render "components/logo-ball", style: "background-color: rgb(239 0 23 / 75%)"%>
      <% end %>
    <% end %>
  </div>
</div>


<h2>Now Availables!</h2>
<%= render "components/card-poke-index", pokemons: @pokemons %>

app/views/pokemons/new.html.erb
<h1>Pokemons#new</h1>
<p>Find me in app/views/pokemons/new.html.erb</p>

app/views/pokemons/show.html.erb
<% if @pokemon.rentings.any? %>
  <h2>My team</h2>
  <div class="d-flex justify-content-around bg-white m-4 p-4 border border-warning border-3 rounded-4">
    <% @pokemon.rentings.each do |renting| %>
      <%= cl_image_tag renting.pokemon.image_url, crop: :thumb, gravity: :faces, height: 40, width: 40, class: "border border-3 border-danger rounded-4" %>
    <% end %>
  </div>
<% end %>




<h2>Want to catch <%= @pokemon.name %>?</h2>


 <%= render "components/card-poke-show", pokemon: @pokemon %>
 <%# <%= render "components/form-renting", rentings: @rentings %>

app/views/pokemons/update.html.erb
<h1>Pokemons#update</h1>
<p>Find me in app/views/pokemons/update.html.erb</p>

app/views/rentings/index.html.erb
<% if @pokemon.rentings.any? %>
  <h2>My team</h2>
  <div class="d-flex justify-content-around bg-white-transparent m-4 p-4 border border-dark border-3 rounded-4">
    <% @pokemon.rentings.each do |renting| %>
      <%= cl_image_tag renting.pokemon.image_url, crop: :thumb, gravity: :faces, height: 40, width: 40, class: "border border-3 border-dark rounded-4" %>
    <% end %>
  </div>
<% end %>




<h2>Want to catch <%= @pokemon.name %>?</h2>


 <%= render "components/card-poke-show", pokemon: @pokemon %>
 <%# <%= render "components/form-renting", rentings: @rentings %>